spring:
    application:
        name: eureka-server # Remplacez par le nom de votre service

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
            register-with-eureka: true
            fetch-registry: true